# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getPIP <- function(seeds, scans, mzs, clu, mztol, gap) {
    .Call('_deblank_getPIP', PACKAGE = 'deblank', seeds, scans, mzs, clu, mztol, gap)
}

waveft <- function(omega, scales) {
    .Call('_deblank_waveft', PACKAGE = 'deblank', omega, scales)
}

cwtft <- function(val) {
    .Call('_deblank_cwtft', PACKAGE = 'deblank', val)
}

localMax <- function(cwt2d) {
    .Call('_deblank_localMax', PACKAGE = 'deblank', cwt2d)
}

localMin <- function(cwt2d) {
    .Call('_deblank_localMin', PACKAGE = 'deblank', cwt2d)
}

ridgesDetection <- function(cwt2d, val) {
    .Call('_deblank_ridgesDetection', PACKAGE = 'deblank', cwt2d, val)
}

peaksPosition <- function(val, ridges, cwt2d) {
    .Call('_deblank_peaksPosition', PACKAGE = 'deblank', val, ridges, cwt2d)
}

getSignal <- function(cwt2d, ridges, peaks) {
    .Call('_deblank_getSignal', PACKAGE = 'deblank', cwt2d, ridges, peaks)
}

